# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octosql < Formula
  desc "OctoSQL is a query tool that allows you to join, analyse and transform data from multiple databases and file formats using SQL."
  homepage "https://github.com/cube2222/octosql"
  version "0.6.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cube2222/octosql/releases/download/v0.6.1/octosql_0.6.1_darwin_arm64.tar.gz"
      sha256 "8ecc374d3ab3a165461edd50865ebcf9713d284a246abf8b46ee1b497478c1c3"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.6.1/octosql_0.6.1_darwin_amd64.tar.gz"
      sha256 "947ed552cba45ef15f929cf8757dc97e3093f3ff0e7ba94af03cfded1553b28c"

      def install
        bin.install "octosql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.6.1/octosql_0.6.1_linux_amd64.tar.gz"
      sha256 "5d4e34096be82607fbe125b5ae9981e5d7ff6bb7e581711d4ef8f60c8ab30290"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cube2222/octosql/releases/download/v0.6.1/octosql_0.6.1_linux_arm64.tar.gz"
      sha256 "d479f2ea5fccb481345f7f25eb36293a5a050575da76cbfb533397d8441c54f6"

      def install
        bin.install "octosql"
      end
    end
  end

  depends_on "graphviz"
end
