# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octosql < Formula
  desc "OctoSQL is a query tool that allows you to join, analyse and transform data from multiple databases and file formats using SQL."
  homepage "https://github.com/cube2222/octosql"
  version "0.7.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cube2222/octosql/releases/download/v0.7.0/octosql_0.7.0_darwin_arm64.tar.gz"
      sha256 "40a1c269a1351c478af2cd819d1fe5cb8dc706810aa77b77f4bc680e213cf5ad"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.7.0/octosql_0.7.0_darwin_amd64.tar.gz"
      sha256 "a3b81cb8bf130a6e3df3d0049b1b7f05abfc7444ae620a6d1970e2f17cc07c32"

      def install
        bin.install "octosql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.7.0/octosql_0.7.0_linux_amd64.tar.gz"
      sha256 "4444d78ca1133a68fcf0f0f1cf40a822179100cf8fbbcac37720c88e681b9dc6"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cube2222/octosql/releases/download/v0.7.0/octosql_0.7.0_linux_arm64.tar.gz"
      sha256 "71b236c87773e2729b77bec69e47fd8d7eafbb5c5422fb2f8223ed426031e258"

      def install
        bin.install "octosql"
      end
    end
  end

  depends_on "graphviz"
end
