# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octosql < Formula
  desc "OctoSQL is a query tool that allows you to join, analyse and transform data from multiple databases and file formats using SQL."
  homepage "https://github.com/cube2222/octosql"
  version "0.4.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.4.1/octosql_0.4.1_darwin_amd64.tar.gz"
      sha256 "fd34759914f98600217a510f75d930aaa7f32fb291bf52c4d8fb39e6c2d96fe7"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cube2222/octosql/releases/download/v0.4.1/octosql_0.4.1_darwin_arm64.tar.gz"
      sha256 "0e25c70ffeb91e3d192de167f12fcae35d81475d2f1c4ede5cb4b51c12285cf8"

      def install
        bin.install "octosql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cube2222/octosql/releases/download/v0.4.1/octosql_0.4.1_linux_amd64.tar.gz"
      sha256 "e41db55510a8c9095e6e337fca925a5e5bd913f0f4a04000dfed30df28f70791"

      def install
        bin.install "octosql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cube2222/octosql/releases/download/v0.4.1/octosql_0.4.1_linux_arm64.tar.gz"
      sha256 "6729337fcb23ec6e2b609995c06f5cd77f909e778c19f23ebd7d76b047f7bc2a"

      def install
        bin.install "octosql"
      end
    end
  end

  depends_on "graphviz"
end
